---

# Ansible
# ansible_user: root
ansible_python_interpreter: /usr/bin/python3

# Docker
docker_version: "5:19.03"

# Kubernetes
kube_version: "1.19"
cni_version: "0.8.7"
master_ip: "{{ ansible_host | default(groups['master'][0]) }}"
network_dir: /etc/kubernetes/network
kubeadmin_config: /etc/kubernetes/admin.conf

# Helm
helm_version: "3.7"

# Go
go_version: "1.17.3"
golangci_lint_version: "v1.43.0"

# Node and NPM
nvm_version: "0.39.0"
node_version: "12.22.7"
npm_version: "6.14.15"
eslint_version: "5.16.0"

# Meepctl
meepctl_lint: "--nolint"
meepctl_node_ip: "{{ ansible_host | default(groups['master'][0]) }}"