# Copyright (c) 2021  InterDigital Communications, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#------------------------------------------------------------------------------
#  NOTES:
#  - Fileserver names must be unique for all fileservers
#  - Service endpoint names must be unique within a service
#  - 'mode' is the access authorization mode
#    -> allow: grant access 
#    -> block: deny access
#    -> verify: obtain session role & verify role-specific access permissions
#  - 'roles' is a map of role permissions
#    -> allow: grant access 
#    -> block: deny access 
#  - Default access mode & role permissions are used when service-specific
#    values are not provided
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
#  DEFAULT PERMISSIONS:
#  Default access mode & permissions for File Server & Service API routes.
#
#  FORMAT:
#  mode: 'verify'         # access authorization mode: allow|block|verify
#  roles:                 # role permissions: allow|block
#    admin: 'allow'
#    user: 'block'
#------------------------------------------------------------------------------
default:
  mode: 'block'

# #------------------------------------------------------------------------------
# #  FILESERVER PERMISSIONS
# #  File Server access permissions.
# #
# #  FORMAT:
# #  - name: 'fs-name'              # fileserver name
# #    path: '/path/to/fs'          # fileserver path
# #    sbox: true|false             # sandbox deployment
# #    mode: 'allow|block|verify'   # access authorization mode
# #    roles:                       # role-specific permissions
# #      admin: 'allow|block'
# #      user: 'allow|block'
# #
# #  !!! IMPORTANT NOTE !!!
# #  Fileserver route matching is performed in the order defined below.
# #  You must place more specific routes first.
# #------------------------------------------------------------------------------
fileservers:
  #------------------------------
  #  Grafana (3rd Party)
  #------------------------------
  - name: 'grafana'
    path: '/grafana'
    mode: 'verify'
    roles:
      admin: 'allow'
      user: 'allow'
  #------------------------------
  #  Swagger UI
  #------------------------------
  - name: 'meep-swagger-ui'
    path: '/api/'
    mode: 'verify'
    roles:
      admin: 'allow'
      user: 'allow'
#   #------------------------------
#   #  Alternate Swagger UI
#   #------------------------------
#   - name: 'meep-alt-swagger-ui'
#     path: '/alt/api/'
#     mode: 'verify'
#     roles:
#       admin: 'allow'
#       user: 'block'
#   #------------------------------
#   #  Alternate Frontend
#   #------------------------------
#   - name: 'meep-alt-frontend'
#     path: '/alt/'
#     mode: 'verify'
#     roles:
#       admin: 'allow'
#       user: 'block'
  #------------------------------
  #  Sandbox Swagger UI (Sbox)
  #------------------------------
  - name: 'meep-sbox-swagger-ui'
    path: '/api/'
    sbox: true
    mode: 'verify'
    roles:
      admin: 'allow'
      user: 'allow'
#   #------------------------------
#   #  Sandbox Alternate Swagger UI (Sbox)
#   #------------------------------
#   - name: 'meep-alt-sbox-swagger-ui'
#     path: '/alt/api/'
#     sbox: true
#     mode: 'verify'
#     roles:
#       admin: 'allow'
#       user: 'block'
  #------------------------------
  #  Frontend (Default)
  #------------------------------
  - name: 'meep-frontend'
    path: '/'
    mode: 'allow'

# #------------------------------------------------------------------------------
# #  SERVICE ENDPOINT PERMISSIONS
# #  Service REST API endpoint access permissions.
# #
# #  FORMAT:
# #  - name: 'svc-name'                   # service name
# #    api: 'api-name'                    # API-specific identifier (when service has multiple APIs)
# #    path: '/svc/base/path'             # service base path
# #    sbox: true|false                   # sandbox deployment
# #    default:                           # default service permissions
# #      mode: 'allow|block|verify'       # access authorization mode
# #      roles:                           # role-specific permissions
# #        admin: 'allow|block'
# #        user: 'allow|block'
# #    endpoints:                         # Endpoint permissions (overrides default)
# #      - name 'endpoint-name'           # endpoint name
# #        path: '/endpoint/path'         # endpoint path
# #        method: 'GET|POST|PUT|DELETE'  # endpoint method
# #        mode: 'allow|block|verify'     # access authorization mode
# #        roles:                         # role-specific permissions
# #          admin: 'allow|block'
# #          user: 'allow|block'
# #    fileservers:                       # Service fileserver permissions (overrides default)
# #      - name 'fs-name'                 # fileserver name
# #        path: '/fs-endpoint/path'      # fileserver endpoint path
# #        mode: 'allow|block|verify'     # access authorization mode
# #        roles:                         # role-specific permissions
# #          admin: 'allow|block'
# #          user: 'allow|block'
# #------------------------------------------------------------------------------
services:
  #------------------------------
  #  MEC Application Support (Sbox)
  #------------------------------
  - name: 'meep-app-enablement'
    api: 'mec_app_support'
    path: '/mec_app_support/v1'
    sbox: true
    default:
      mode: 'verify'
      roles:
       admin: 'allow'
       user: 'allow'
  #------------------------------
  #  MEC Service Management (Sbox)
  #------------------------------
  - name: 'meep-app-enablement'
    api: 'mec_service_mgmt'
    path: '/mec_service_mgmt/v1'
    sbox: true
    default:
      mode: 'verify'
      roles:
        admin: 'allow'
        user: 'allow'
  #------------------------------
  #  GIS Engine (Sbox)
  #------------------------------
  - name: 'meep-gis-engine'
    path: '/gis/v1'
    sbox: true
    default:
      mode: 'verify'
      roles:
        admin: 'allow'
        user: 'allow'
  #------------------------------
  #  Location Service (Sbox)
  #------------------------------
  - name: 'meep-loc-serv'
    path: '/location/v2'
    sbox: true
    default:
      mode: 'verify'
      roles:
        admin: 'allow'
        user: 'allow'
  #------------------------------
  #  Metrics Engine (Sbox)
  #------------------------------
  - name: 'meep-metrics-engine'
    path: '/metrics/v2'
    sbox: true
    default:
      mode: 'verify'
      roles:
        admin: 'allow'
        user: 'allow'
  #------------------------------
  #  Mobility Group Manager (Sbox)
  #------------------------------
  - name: 'meep-mg-manager'
    path: '/mgm/v1'
    sbox: true
    default:
      mode: 'verify'
      roles:
        admin: 'allow'
        user: 'allow'
  #------------------------------
  #  Monitoring Engine
  #------------------------------
  - name: 'meep-mon-engine'
    path: '/mon-engine/v1'
    sbox: false
    default:
      mode: 'verify'
      roles:
        admin: 'allow'
        user: 'allow'
  #------------------------------
  #  Platform Controller
  #------------------------------
  - name: 'meep-platform-ctrl'
    path: '/platform-ctrl/v1'
    sbox: false
    default:
      mode: 'verify'
      roles:
        admin: 'allow'
        user: 'allow'
  #------------------------------
  #  RNI Service (Sbox)
  #------------------------------
  - name: 'meep-rnis'
    path: '/rni/v2'
    sbox: true
    default:
      mode: 'verify'
      roles:
        admin: 'allow'
        user: 'allow'
  #------------------------------
  #  Sandbox Controller (Sbox)
  #------------------------------
  - name: 'meep-sandbox-ctrl'
    path: '/sandbox-ctrl/v1'
    sbox: true
    default:
      mode: 'verify'
      roles:
        admin: 'allow'
        user: 'allow'
  #------------------------------
  #  WAI Service (Sbox)
  #------------------------------
  - name: 'meep-wais'
    path: '/wai/v2'
    sbox: true
    default:
      mode: 'verify'
      roles:
        admin: 'allow'
        user: 'allow'
    fileservers:
      - name: 'Websocket'
        path: '/ws'
        mode: 'allow'
  #------------------------------
  #  AMSI Service (Sbox)
  #------------------------------
  - name: 'meep-ams'
    path: '/amsi/v1'
    sbox: true
    default:
      mode: 'verify'
      roles:
        admin: 'allow'
        user: 'allow'

