---
- name: Chmod
  shell: "chown -R {{ ansible_user }} /bin"

- name: Update profile gopath
  become: false
  lineinfile:
    dest: /home/{{ ansible_user }}/.profile
    state: present
    line: 'export GOPATH=$HOME/gocode'

- name: Update profile path
  become: false
  lineinfile:
    dest: /home/{{ ansible_user }}/.profile
    state: present
    line: 'export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin'
    
- name: Update bashrc gopath
  become: false
  lineinfile:
    dest: /home/{{ ansible_user }}/.bashrc
    state: present
    line: 'export GOPATH=$HOME/gocode'

- name: Update bashrc path
  become: false
  lineinfile:
    dest: /home/{{ ansible_user }}/.bashrc
    state: present
    line: 'export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin'

- name: Install meepctl
  become: false
  shell: "cd /home/{{ ansible_user }}/AdvantEDGE/go-apps/meepctl; ./install.sh; export PATH=$PATH:/bin/meepctl"

- name: Config meepctl
  shell: "meepctl config ip {{ meepctl_node_ip }}; meepctl config gitdir /home/{{ ansible_user }}/AdvantEDGE"

- name: Show meepctl config
  become: false
  shell: "meepctl config"
  register: command_output_meepctl_config

- name: Debug command_output_meepctl_config
  debug:
    var: command_output_meepctl_config

- name: Meepctl deploy dependencies
  become: false
  shell: "meepctl deploy dep"

- name: Meepctl build
  become: false
  shell: "meepctl build all {{ meepctl_lint }}"


- name: Meepctl dockerize
  become: false
  shell: "meepctl dockerize all"

- name: Verify dockerize
  become: false
  shell: "docker images | grep meep"
  register: command_output_docker_images_meep

- name: Debug command_output_docker_images_meep
  become: false
  debug:
    var: command_output_docker_images_meep

- name: Meepctl deploy core
  become: false
  shell: "meepctl deploy core"

