---

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - build-essential
    - libssl-dev

- name: "Install NVM"
  shell: "wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh | bash"
  tags: node

- name: "Update path from NVM"
  shell: 'export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm'
  tags: node
  
- name: Install node
  become: false
  shell: "nvm install {{ node_version }}"

- name: Install npm and eslint
  become: false
  shell: "npm install -g eslint@{{ eslint_version }} && npm install -g eslint-plugin-react"
