---

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - build-essential
    - libssl-dev

- name: Install NVM
  shell: "wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh | bash"
  tags: node

- name: Install NVM path
  shell: "bash /home/{{ ansible_user }}/AdvantEDGE/playbooks/roles/node/files/install_path_nvm.sh"
  tags: node

- name: Install node
  become: no
  shell: /bin/bash -c "source /home/{{ ansible_user }}/.nvm/nvm.sh && npm install -g npm@{{ npm_version }} && npm install -g eslint@{{ eslint_version }} && npm install -g eslint-plugin-react"
  tags: node

# - name: Install npm and eslint
#  become: no
#  shell: "npm install -g eslint@{{ eslint_version }} && npm install -g eslint-plugin-react"
#  tags: node
