---

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - build-essential
    - libssl-dev

- name: Uninstall NVM
  shell: "rm -rf /home/{{ ansible_user }}/.nvm"
  tags: node

- name: Install NVM
  become: no
  shell: "wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh | bash"
  tags: node

- name: Check NVM sinlink
  shell: "find / -type l | grep nvm"
  tags: node

- name: Install NVM path
  become: no
  shell: "bash /home/{{ ansible_user }}/AdvantEDGE/playbooks/roles/node/files/install_path_nvm.sh"
  tags: node


- name: Install node
  become: no
  shell: "nvm install {{ node_version }}"
  tags: node

- name: Install npm and eslint
  become: no
  shell: "npm install -g eslint@{{ eslint_version }} && npm install -g eslint-plugin-react"
  tags: node
